### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by enesoztrk** [Polo123456789/cmm-#3]
Hello,

I am trying to compile the project. But it gives "No such file or directory" errors. Should I add directories in CMakeLists.txt file? Or is there anything wrong with what I did?

![image](https://user-images.githubusercontent.com/23314775/124355187-9a3dcf80-dc18-11eb-8082-a49d04a3aa86.png)

**Comment by Polo123456789** [comment]
Hi, glad to see that you are interested in the project.

It seems like your IDE is not identifying correctly the include paths of the
files.

Currently, I'm missing some information to give a solution to the problem.

Could you tell me:

1. The IDE and compiler you are using?
2. How did you generate the project?

**Comment by enesoztrk** [comment]
Hi,
1. I am using QT Creator IDE with CMake.
2. with CMake.

**Comment by Polo123456789** [comment]
> I am using QT Creator IDE with CMake.

Have vey little experience with QT Creator, but I will try to help.

> with CMake.

Did you do it this way?

~~~shell
mkdir bin
cd bin
cmake ..
~~~

Or [this way?](https://doc.qt.io/qtcreator/creator-project-opening.html).

**Comment by enesoztrk** [comment]
Thank you for the help. Fortunately, I have done the build process in QT creator IDE. I will try to implement "indented_code_block" feature under Component filtering. Is it ok for you?

**Comment by Polo123456789** [comment]
Yea, feel free to do it.  If you have any questions feel free to ask here.
